version: '3.9'
services:
  mysql:
    image: mysql:8-oracle
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: mysql ogn --user=root --password='${MYSQL_PASSWORD:-PS=FT7O99HQIA5}' --silent --execute "SELECT 1;"
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD:-PS=FT7O99HQIA5}"
    volumes:
      - ./conf/sql/docker:/docker-entrypoint-initdb.d
  next:
    build:
      context: .
      dockerfile: ./conf/Dockerfile-fe
      args:
        NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN: ${NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN?Mapbox token must be set}
    command: yarn next start
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-PS=FT7O99HQIA5}
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_DATABASE: ogn
      NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN: ${NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN?Mapbox token must be set}
      NEXT_SCORE_REFRESH_INTERVAL: $NEXT_SCORE_REFRESH_INTERVAL
    restart: always
  ogn:
    build: 
      dockerfile: ./conf/Dockerfile-be
    command: node bin/ogn.js
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-PS=FT7O99HQIA5}
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_DATABASE: ogn
      NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN: $NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN
      NEXT_PUBLIC_SITEURL: $NEXT_PUBLIC_SITEURL
      NEXT_SCORE_REFRESH_INTERVAL: ${NEXT_SCORE_REFRESH_INTERVAL:-60000}
      API_HOSTNAME: next:3000
  rst:
    build: 
      dockerfile: ./conf/Dockerfile-be
    command: node bin/rst.js
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-PS=FT7O99HQIA5}
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_DATABASE: ogn
      NEXT_PUBLIC_SITEURL: $NEXT_PUBLIC_SITEURL
      RST_URL: ${RST_URL?RST_URL not set}
  apache:
    build: ./conf/apache
    restart: always
    tty: true
    stdin_open: true
    depends_on:
      - next
      - ogn
    ports:
      - 8080:8000
